### ISSUE TITLE
[PATCH] Protect active parser from being freed. [rt.cpan.org #115034]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTML-Parser#15]
Migrated from [rt.cpan.org#115034](https://rt.cpan.org/Ticket/Display.html?id=115034) (status was 'open')

Requestors:
* 'spro^^*%*^6ut#@&$%*c

Attachments:
* [open_TtcpFITu.txt](https://rt.cpan.org/Ticket/Attachment/1634401/875999/open_TtcpFITu.txt)

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2016-06-03 13:33:47
:
```

```

From nicolas@atoomic.org on 2020-08-24 16:17:42
:
```
On Fri Jun 03 09:33:47 2016, SPROUT wrote:
> This is a follow-up to
> <http://www.nntp.perl.org/group/perl.libwww/;msgid=7A27BD12-BA67-40B7-
> 9052-334CCE2C14DA@cpan.org>, from 6 years ago, but this time with a
> patch!
> 
> If you try to free the parser from a callback, it crashes, because
> pstate gets freed while things in the parser are still referring to
> it.


opened PR with this change and unit test as this is still an issue and generating a SEGV
view: https://github.com/gisle/html-parser/pull/13

```

**Comment by genio** [comment]
Fixed in 3.73 (via https://github.com/libwww-perl/HTML-Parser/commit/4e453608d13a495ed2365d6c663bbbbcab254f1f) out in the wild. Thank you!
