### ISSUE TITLE
Should META.json be in source control?

### ISSUE THREAD

**Issue by toddr** [libwww-perl/HTML-Parser#18]

**Comment by karenetheridge** [comment]
For what purpose?

**Comment by genio** [comment]
@toddr For the purposes of CI, yes. It makes CI testing quite a bit simpler.

**Comment by toddr** [comment]
Thanks!

**Comment by toddr** [comment]
In case you want it, I'm passing you a PR with a workflow that will just use cpanfile

https://github.com/libwww-perl/HTML-Parser/pull/20
