### ISSUE TITLE
comparing entities with space padding

### ISSUE THREAD

**Issue by thisname12345** [libwww-perl/HTML-Parser#24]
`&#039;` != `&#39;` as a hash key anyway anyone any ideas as to where to bring this issue up?

**Comment by oalders** [comment]
I can't quite tell if this is spam or a real issue. Some context is required to understand the problem. A code snippet to reproduce the warning would be a good start.

**Comment by thisname12345** [comment]
its mostly spam they are the same hash keys you can change the equality with a use Text::Unaccent::PurePerl qw(unac_string); its getting out of a tangle with F4 being ascii C3 B4 being utf-8 displayed as ÃŽ ?? anyway

**Comment by oalders** [comment]
Fascinating. Tell me more?

**Comment by oalders** [comment]
A code snippet to reproduce the warning would be a good start.
